---
title: Stackbit Azimuth Theme
baseURL: "/"
params:
  palette: blue
  header:
    title: ''
    logo_img: ''
    has_nav: true
    nav_links:
    - label: Home
      url: "/"
  footer:
    logo_img: ''
    tagline: ''
    has_nav: true
    nav_title: Company
    nav_links:
    - label: Contact
      url: "/contact"
    has_social: true
    social_title: Community
    social_links: []
    has_subscribe: true
    subscribe_title: Subscribe
    subscribe_content: ''
    content: ''
    links: []
disableKinds:
- RSS
- taxonomy
- taxonomyTerm
